### ISSUE TITLE
Router needs to support versioning

### ISSUE THREAD

**Issue by davismj** [aurelia/app-documentation#4]
`/#/api/binding/0.8.2` needs to route to docs for 0.8.2. This should be hooked up to a select on the page. 

Additionally, defaults need to be implemented. Navigating to /#/api needs to route to the first(?) module and /#/api/binding needs to navigate to the master.

**Comment by EisenbergEffect** [comment]
Since we are following semantic versioning, we will actually only need to show and link to major and minor versions. 1.0, 1.1, 1.2. We don't need the patch versions listed or in your linking system since they will only contain patches and never new features or api breaks. What we should do is always take the docs from the latest patch release for any version that is requested though, just in case there are corrections in the docs themselves. Does that make sense?

**Comment by davismj** [comment]
Yes, will do.

**Comment by EisenbergEffect** [comment]
Docs app is handling version on everything now.
