### ISSUE TITLE
Should leverage a general aurelia-wide css library

### ISSUE THREAD

**Issue by davismj** [aurelia/app-documentation#5]
This is low priority and can be deferred until later. However, at some point we will want to sync the specific styles on this app with a general aurelia-wide css framework. @Aaike and I will collaborate on this.

**Comment by EisenbergEffect** [comment]
@davismj What is the current strategy/status of the styles for the docs app? @PWKad is trying to move ahead implementing the api docs, but I think he's got some missing style capabilities that he needs to move forward. @PWKad Can you comment in more detail below? Let's see what we need to move forward. Only about a month left before we need to have this ready to launch...

**Comment by PWKad** [comment]
I think we are missing a lot of basic styles that we take for granted at this point.

From the get-go -

1. A grid system.  Some responsive way of laying out the content areas.  **This is the biggest need**
2. Tables.  We could just use the grid system if we want to stay clear of tables of data.
3. Button states.  Disabled, different sizes
4. Variables for colors.  Right now all of the colors are directly used, need to extract them into a partial or something.

If we don't have anything that's actively being developed I highly suggest we use PureCSS or something for the content areas and leave the existing styles as-is so we can meet the deadline.

**Comment by davismj** [comment]
@Aaike is building something independently, but busy. @joelcoxokc and @scriswell are building an Aurelia official style. I'd be glad to help build that and leverage that, but I haven't been able to get that conversation off the ground.

**Comment by EisenbergEffect** [comment]
It sounds like @Aaike may be too busy at the moment to assist in the way we thought initially. @davismj What do you recommend so that we can move forward? Should we just drop bootstrap back in for now? Or use Pure? We can switch things up later once we have something official, but for now, we need to be able to get the docs up and running within the next 4 weeks, so we can tweak them and author new content for a couple weeks before beta release. Thoughts?

**Comment by davismj** [comment]
@pwkad is on leveraging the new api.json to get the functionality in place, i'll roll custom styles on them for the time being. I recommend we dogfood the official aurelia css as soon as possible

**Comment by PWKad** [comment]
For now let's use flexboxgrid for the grid system and I've hoisted some of the typography styles so they apply more globally.  Should be easy to remove later.

**Comment by joelcoxokc** [comment]
@PWKad @davismj I have a Flexbox Grid I will Share. Please don't use the Flex-box Grid. It actually has some reflowing issues!

**Comment by joelcoxokc** [comment]
@EisenbergEffect @PWKad @davismj 

Sorry I wish they had @/all

I have been in dialogue with the Boubon.io team over Creating an extensive yet Light Weight Grid system. I Have a small implementation I am using in AI. I will try to package it up this weekend, and send you the CSS and the customizable SCSS, 

I am not sure if you want the customElements just yet. 

Infact another team that is doing something similar, is BootStrap 4.0. There grid is very similar to the one I am creating... 

Let me know what you think about BootStraps and in the mean time, I will try to get my grid to you. 

@davismj the CSS is coming very soon. There are a few edge cases I need to cover. But should be soon.

**Comment by Aaike** [comment]
hey guys sorry for droping the ball on this one, have been busy but really trying to clear my schedule to regularly have time again for Aurelia.
I just wanted to suggest Post CSS in general , Bootstrap 5.0 will be using it and some major companies have already adopted it.
i was in fact thinking on converting my stuff to pure post css as it supports esnext and a lot of css4 capabilities with fallback for older browsers.
https://github.com/postcss/postcss
there is also a video presentation about it somewhere on youtube

This way you don't have to create a scss , less or stylus version , everything is done in post and people can still choose to use either one of the preprocessors or just use the postprocessor for their custom styles.

**Comment by joelcoxokc** [comment]
@Aaike Good Call. 

I am a huge advocate for POST/Next technologies. I am glad you are making the suggestion! PostCss is great, it allows an insane amount of customization!

I know this discussion is not about AI... However, I was writing with Less to begin with. I then moved to PostCss. I took a deep dive, Trying out all their plugins/modules. I even created a few of my own. 
PostCss is a great tool. Although It was through PostCss that I was introduced to some of Scss's New technologies, Like the Sass Maps, and a few other things I things I needed, that were not provided. 

Some functionality just has not be perfected just Yet. **This does not mean I have completely written it off**, But I have put it aside. I know that with AI we want to provide the ability to use any Preprocessor.. (Less may be difficult), But I am so deep into Sass at this point. I would only loose time. 

Another reason why I chose Sass over PostCss is because AI needs to be **Top Notch**, **Supported** and **Compatible**, **Production Ready**, and especially **Client Ready**. The community for PostCss is still fairly small... So I felt it a little unwise to build something production Level on it just yet. 

It would almost be similar to me beginning AI back during Aurelia's early stages.

Any way! I definitely Support PostCss Though. @davismj If you guys want to use PostCSS on the app-documentation... I Still have not removed Post CSS from my project/gulp tasks. I can easily swap my mixins for the **Grid** over to PostCss mixins. Just Let me know. 

@Aaike  What do you think? Feedback? Thoughts?

**Comment by Aaike** [comment]
yes good call, i agree that PostCSS still is in it's baby shoes, it's just something to keep an eye out for.. going with Sass will definitly give you the best compatibility and maturity at the moment.

**Comment by EisenbergEffect** [comment]
Closing for now. We have some of this in the docs app and Joel is working on AI in general. Once that gets a bit farther along we'll see what parts will be open vs. commercial.
